# https://docs.readthedocs.io/en/latest/config-file/index.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"  # sphinx-build: cgi module was removed in 3.13

formats:
  - htmlzip
  - epub

python:
  install:
    - requirements: docs-requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
